'use strict';
(() => {
  const $=id=>document.getElementById(id),types={trade:'交換',offer:'譲る',want:'求める'},delivery={meetup:'現地交換',mail:'郵送',either:'現地・郵送'};
  let user=null,profile=null,groups=[],idols=[],events=[],posts=[],saved=new Set(),busy=false;
  function option(label,value=''){return new Option(label,value)}
  function button(label,handler,className=''){const b=document.createElement('button');b.type='button';b.textContent=label;b.className=className;b.onclick=handler;return b}
  function refreshDependentOptions(){const gid=$('groupSelect').value;$('idolSelect').replaceChildren(option('指定しない'),...idols.filter(x=>x.group_id===gid).map(x=>option(x.name,x.id)));$('eventSelect').replaceChildren(option('指定しない'),...events.filter(x=>x.group_id===gid).map(x=>option(`${x.title} · ${x.venue}`,x.id)))}
  async function loadCatalog(){const [g,i,e]=await Promise.all([otakuSupabase.from('otaku_idol_groups').select('id,name').eq('publication_status','published').eq('is_demo',false).order('name'),otakuSupabase.from('otaku_idols').select('id,name,group_id').eq('publication_status','published').eq('is_demo',false).order('name'),otakuSupabase.from('otaku_events').select('id,title,venue,group_id').eq('publication_status','published').eq('is_demo',false).order('starts_at',{ascending:false}).limit(200)]);groups=g.data||[];idols=i.data||[];events=e.data||[];$('groupSelect').replaceChildren(option('グループを選択'),...groups.map(x=>option(x.name,x.id)));$('groupFilter').replaceChildren(option('全グループ'),...groups.map(x=>option(x.name,x.id)));refreshDependentOptions()}
  async function load(){if(!user){$('posts').textContent='募集を見るにはログインしてください。';return}const [p,s]=await Promise.all([otakuSupabase.from('otaku_goods_posts').select('id,user_id,group_id,idol_id,event_id,trade_type,item_name,description,delivery_method,meetup_prefecture,status,created_at,otaku_profiles(display_name,username),otaku_idol_groups(name),otaku_idols(name),otaku_events(title,venue)').order('created_at',{ascending:false}).limit(100),otakuSupabase.from('otaku_saved_goods_posts').select('post_id').eq('user_id',user.id)]);if(p.error){$('posts').textContent='募集を読み込めませんでした。';return}posts=p.data||[];saved=new Set((s.data||[]).map(x=>x.post_id));render()}
  function render(){const q=$('search').value.trim().toLowerCase(),type=$('typeFilter').value,gid=$('groupFilter').value;const rows=posts.filter(x=>(!q||[x.item_name,x.description,x.otaku_profiles?.display_name,x.otaku_idol_groups?.name,x.otaku_idols?.name].join(' ').toLowerCase().includes(q))&&(!type||x.trade_type===type)&&(!gid||x.group_id===gid)&&(!$('savedOnly').checked||saved.has(x.id)));$('posts').replaceChildren();if(!rows.length){$('posts').textContent='条件に合う募集はありません。';return}for(const post of rows)$('posts').append(renderPost(post))}
  function renderPost(post){const article=document.createElement('article');article.className='post';const meta=document.createElement('div');meta.className='meta';const profile=document.createElement('a');profile.href=`user.html?id=${encodeURIComponent(post.user_id)}`;profile.textContent=post.otaku_profiles?.display_name||post.otaku_profiles?.username||'ユーザー';meta.append(profile,` · ${new Date(post.created_at).toLocaleString('ja-JP')}`);const title=document.createElement('h3');title.textContent=post.item_name;const desc=document.createElement('div');desc.textContent=post.description;desc.style.whiteSpace='pre-wrap';const tags=document.createElement('div');tags.className='tags';const values=[types[post.trade_type],post.otaku_idol_groups?.name,post.otaku_idols?.name,delivery[post.delivery_method],post.meetup_prefecture,post.otaku_events?.title,post.status==='negotiating'?'交渉中':post.status==='closed'?'終了':null].filter(Boolean);for(const value of values){const tag=document.createElement('span');tag.className='tag';tag.textContent=value;tags.append(tag)}const actions=document.createElement('div');actions.className='actions';if(post.user_id===user.id){if(post.status==='open')actions.append(button('交渉中にする',()=>changeStatus(post,'negotiating')));if(post.status==='negotiating')actions.append(button('募集中に戻す',()=>changeStatus(post,'open')));if(post.status!=='closed')actions.append(button('募集を終了',()=>changeStatus(post,'closed'),'danger'));actions.append(button('削除',()=>removePost(post),'danger'))}else{actions.append(button('メッセージを送る',()=>message(post)));const save=button(saved.has(post.id)?'保存済み ★':'募集を保存',()=>toggleSave(post,save),saved.has(post.id)?'saved':'');actions.append(save,button('通報',()=>otakuReportContent('goods',post.id)),button('ブロック',()=>OtakuSafety.block(post.user_id,load),'danger'))}article.append(meta,title,desc,tags,actions);return article}
  async function toggleSave(post,control){control.disabled=true;const exists=saved.has(post.id);const query=otakuSupabase.from('otaku_saved_goods_posts');const result=exists?await query.delete().eq('user_id',user.id).eq('post_id',post.id):await query.insert({user_id:user.id,post_id:post.id});if(!result.error){exists?saved.delete(post.id):saved.add(post.id);render()}else{control.disabled=false;alert('保存状態を変更できませんでした。')}}
  async function changeStatus(post,status){if(status==='closed'&&!confirm('募集を終了しますか？すでに始まったDMは引き続き利用できます。'))return;const {data,error}=await otakuSupabase.from('otaku_goods_posts').update({status}).eq('id',post.id).eq('user_id',user.id).select('id');if(error||!data?.length)alert('募集状態を変更できませんでした。');else await load()}
  async function removePost(post){if(!confirm('募集と、この募集から始まったDMを削除しますか？'))return;const {error}=await otakuSupabase.from('otaku_goods_posts').delete().eq('id',post.id).eq('user_id',user.id);if(error)alert('募集を削除できませんでした。');else await load()}
  async function message(post){if(!profile){location.href=otakuProfileUrl(location.href);return}let result=await otakuSupabase.from('otaku_conversations').select('id').eq('goods_post_id',post.id).eq('requester_user_id',user.id).maybeSingle();if(result.data?.id){location.href=`chat.html?id=${encodeURIComponent(result.data.id)}`;return}const payload={goods_post_id:post.id,event_id:post.event_id||null,owner_user_id:post.user_id,requester_user_id:user.id};result=await otakuSupabase.from('otaku_conversations').insert(payload).select('id').single();if(result.error){const retry=await otakuSupabase.from('otaku_conversations').select('id').eq('goods_post_id',post.id).eq('requester_user_id',user.id).maybeSingle();if(retry.data?.id){location.href=`chat.html?id=${encodeURIComponent(retry.data.id)}`;return}alert(OtakuSafety.errorText(result.error));return}location.href=`chat.html?id=${encodeURIComponent(result.data.id)}`}
  $('deliveryMethod').onchange=()=>{$('prefectureField').hidden=$('deliveryMethod').value==='mail'};$('groupSelect').onchange=refreshDependentOptions;for(const id of ['search','typeFilter','groupFilter','savedOnly'])$(id).addEventListener(id==='search'?'input':'change',render);
  $('createPost').onclick=async()=>{if(busy)return;const payload={user_id:user.id,group_id:$('groupSelect').value,idol_id:$('idolSelect').value||null,event_id:$('eventSelect').value||null,trade_type:$('tradeType').value,item_name:$('itemName').value.trim(),description:$('description').value.trim(),delivery_method:$('deliveryMethod').value,meetup_prefecture:$('deliveryMethod').value==='mail'?null:$('meetupPrefecture').value.trim()};if(!payload.group_id||!payload.item_name||!payload.description||((payload.delivery_method==='meetup'||payload.delivery_method==='either')&&!payload.meetup_prefecture)){$('formStatus').textContent='グループ、グッズ名、説明、現地交換の都道府県を入力してください。';return}busy=true;$('createPost').disabled=true;const {error}=await otakuSupabase.from('otaku_goods_posts').insert(payload);$('formStatus').textContent=error?'募集を公開できませんでした。':'募集を公開しました。';if(!error){$('itemName').value='';$('description').value='';await load()}busy=false;$('createPost').disabled=false};
  (async()=>{user=await otakuGetUser();if(!user){$('gate').append('利用するには');const a=document.createElement('a');a.href=otakuLoginUrl(location.href);a.textContent='ログイン';$('gate').append(a,'してください。');return}profile=await otakuGetProfile(user.id);if(!profile){$('gate').textContent='募集やDMを利用するにはプロフィールを作成してください。';const a=document.createElement('a');a.href=otakuProfileUrl(location.href);a.textContent=' プロフィールを作成';$('gate').append(a)}else{$('gate').textContent='ログイン中';$('composer').hidden=false}await loadCatalog();await load()})();
})();
