'use strict';
(()=>{
  const $=id=>document.getElementById(id),fieldIds=['venueName','prefecture','city','nearestStation','accessNotes','lockers','toilets','convenienceStore','meetingSpot','officialUrl'];
  let user=null,editing=null,rows=[],busy=false;
  function value(id){return $(id).value.trim()||null}
  function setBusy(next){busy=next;$('save').disabled=next;$('reset').disabled=next}
  function reset(){editing=null;$('editor').reset();$('editorTitle').textContent='新規登録';$('lastChecked').textContent='';$('message').textContent=''}
  function edit(row){editing=row;const map={venueName:'venue_name',prefecture:'prefecture',city:'city',nearestStation:'nearest_station',accessNotes:'access_notes',lockers:'lockers',toilets:'toilets',convenienceStore:'convenience_store',meetingSpot:'meeting_spot',officialUrl:'official_url'};for(const id of fieldIds)$(id).value=row[map[id]]||'';$('publicationStatus').value=row.publication_status;$('verified').checked=false;$('lastChecked').textContent=`前回確認: ${new Date(row.source_checked_at).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}`;$('editorTitle').textContent=`編集: ${row.venue_name}`;$('editorTitle').scrollIntoView({behavior:'smooth'})}
  function render(){const q=$('search').value.trim().toLowerCase(),list=rows.filter(row=>[row.venue_name,row.prefecture,row.city].join(' ').toLowerCase().includes(q));$('records').replaceChildren(...list.map(row=>{const item=document.createElement('div');item.className='record';const text=document.createElement('div');text.textContent=row.venue_name;const sub=document.createElement('div');sub.className='note';sub.textContent=`${row.prefecture||''} ${row.city||''} · ${row.publication_status==='published'?'公開':row.publication_status==='draft'?'下書き':'非公開'}`;text.append(sub);const button=document.createElement('button');button.type='button';button.textContent='編集';button.onclick=()=>edit(row);item.append(text,button);return item}));if(!list.length)$('records').textContent='登録済みの会場はありません。'}
  async function load(){const {data,error}=await otakuSupabase.from('otaku_venue_guides').select('*').order('venue_name').limit(300);if(error)throw error;rows=data||[];render()}
  $('editor').onsubmit=async event=>{event.preventDefault();if(busy)return;$('message').textContent='';try{if(!$('verified').checked)throw new Error('公式情報を確認したチェックを入れてください。');const officialUrl=OtakuCatalog.sourceUrl(value('officialUrl'));if(!officialUrl)throw new Error('会場公式URLを入力してください。');const payload={venue_name:value('venueName'),prefecture:value('prefecture'),city:value('city'),nearest_station:value('nearestStation'),access_notes:value('accessNotes'),lockers:value('lockers'),toilets:value('toilets'),convenience_store:value('convenienceStore'),meeting_spot:value('meetingSpot'),official_url:officialUrl,source_checked_at:new Date().toISOString(),publication_status:$('publicationStatus').value,updated_by:user.id};if(!payload.venue_name)throw new Error('会場名を入力してください。');if(payload.publication_status==='published'&&!confirm('確認済みの会場ガイドを公開しますか？'))return;setBusy(true);let query=otakuSupabase.from('otaku_venue_guides');query=editing?query.update(payload).eq('id',editing.id):query.insert(payload);const {data,error}=await query.select('id');if(error)throw error;if(data.length!==1)throw new Error('保存対象を確認できませんでした。');reset();await load();$('message').textContent='保存しました。'}catch(error){$('message').textContent=error.code==='23505'?'同じ会場のガイドが登録済みです。':error.code==='42501'?'管理者権限がありません。':error.message||'保存できませんでした。'}finally{setBusy(false)}};
  $('reset').onclick=reset;$('search').oninput=render;
  (async()=>{try{user=await otakuGetUser();if(!user){$('gate').textContent='管理者アカウントでログインしてください。';return}const {data,error}=await otakuSupabase.rpc('otaku_is_catalog_admin');if(error||!data){$('gate').textContent='このアカウントには管理権限がありません。';return}$('gate').hidden=true;$('workspace').hidden=false;await load()}catch{$('gate').textContent='管理者権限または会場情報を確認できませんでした。'}})();
})();
